require:
  - rubocop-rails
  - rubocop-minitest

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'config/environments/development.rb'