version: '3'

services:
  redis:
    image: redis
    command: redis-server
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  redis_data:
